name: Build & Deploy Image

# Runs only on request
on:
  workflow_dispatch:
  push:
    branches:
      develop
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: node_modules/@angular/cli/bin/ng build

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: /usr/bin/docker build . --platform=linux/arm64 -t anesi/shopping-list-fe:latest

      - name: Push Docker image
        run: /usr/bin/docker push anesi/shopping-list-fe:latest

  deploy:
    runs-on: orangepi-runner
    if: success()
    steps:
      - name: Pull image
        run: sudo docker pull anesi/shopping-list-fe:latest

      - name: Stop old container
        run: sudo docker container stop shopping-list-fe

      - name: Remove old container
        run: sudo docker container rm shopping-list-fe

      - name: Start new container
        run: sudo docker run --name shopping-list-fe -p 80:80 -p 443:443 --detach anesi/shopping-list-fe:latest
