# This is a basic workflow to help you get started with Actions

name: Build Docker Image

# Runs only on request
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: node_modules/@angular/cli/bin/ng build

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: /usr/bin/docker build . --platform=linux/arm64 -t anesi/shopping-list-fe:latest

      - name: Push Docker image
        run: /usr/bin/docker push anesi/shopping-list-fe:latest
