# This is a basic workflow to help you get started with Actions

name: Deploy

# Runs only on request
on:
  workflow_run:
    workflows: [ "Build Docker Image" ]
    types:
      - completed
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: orangepi-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Pull image
        run: sudo docker pull anesi/shopping-list-fe:latest

      - name: Stop old container
        run: sudo docker container stop shopping-list-fe

      - name: Remove old container
        run: sudo docker container rm shopping-list-fe

      - name: Start new container
        run: sudo docker run --name shopping-list-fe --link shopping-list-be:shopping-list-be -p 8080:8080 --detach anesi/shopping-list-fe:latest
