# This is a basic workflow to help you get started with Actions

name: Deploy

# Runs only on request
on:
  workflow_run:
    workflows: [ "Build Docker Image" ]
    types:
      - completed
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: orangepi-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Pull image
        run: docker pull anesi/shopping-list-fe:latest

      - name: Stop old container
        run: docker container stop shopping-list-fe

      - name: Remove old container
        run: docker container rm shopping-list-fe

      - name: Start new container
        run: docker run --name shopping-list-fe -p 80:80 -p 443:443 --detach anesi/shopping-list-fe:latest
